### ISSUE TITLE
bug with overview plugin

### ISSUE THREAD

**Issue by emberauclair** [mulfok/periodic-note-templates#2]
I tried to use your weekly note template, but I'm having trouble getting it to work. it seems like the error thrown is a bug. 
![unknown](https://user-images.githubusercontent.com/82671168/160261217-db6aaf5e-6ee3-4e0b-b744-f1a31e1f4e66.png)

**Comment by mulfok** [comment]
From what I said on Discord:

> To use this template, you need to have the **Periodic Notes** plugin installed, and configured to use the daily note and weekly note templates from the repo; AND you need the **Templater** plugin-- make sure "trigger on file creation" is turned on in settings

> The reason the error is there is because some of the code in the template is actually inline Templater queries, which won't work in the chart code. Once the daily note is created from the template though, it replaces those queries with what should be there, and the chart will render. Same to the dataview table

I additionally forgot to mention, `window.renderChart is not a function` may suggest that you don't have the **Obsidian Charts** plugin installed, which is required for the chart to be rendered. Let me know if you have any problems from this point on, and I'll do my best to help you out with it!

**Comment by Gourav1910** [comment]
I tried what you suggest here i.e. Templater plugin-- make sure "trigger on file creation" is turned on in settings, Periodic Notes plugin installed.

But still error is showing

![Pasted image 20220510075622](https://user-images.githubusercontent.com/101202140/167530482-51944623-b2a4-4b37-9337-0cbfbb47d602.png)
